Enhance UI + Add token screen
lethuccrma/react-native-sample pull request #3
Opened 2022-07-05 15:43 UTC by lethuccrma

- Enhance Login screen
- Add token screen
- Show added toke

https://user-images.githubusercontent.com/105472435/177366077-a8bcc5c0-a4af-4ec2-a3fb-8e1f0f66608a.mp4

ns

2022-07-05 16:42 UTC, lytienphuc0810 requested changes

2022-07-05 16:42 UTC, lytienphuc0810 commented on .eslintrc.js
> +    'no-param-reassign': 'warn',
this should not be bypassed

2022-07-05 16:42 UTC, lytienphuc0810 commented on .eslintrc.js
> +    'import/no-cycle': 'warn',
this also should not be bypassed. Circular dependency is very bad

2022-07-05 16:42 UTC, lytienphuc0810 commented on .eslintrc.js
> +    'no-param-reassign': 'warn',
Params should be treated as const

2022-07-06 03:19 UTC, lethuccrma commented
Hi a @lytienphuc0810 . All issues have been fixed without bypassing eslint rules

2022-07-06 04:54 UTC, lytienphuc0810 approved these changes

2022-07-06 07:08 UTC, merged